### ISSUE TITLE
Have you tried SLF4J 2.0.0?

### ISSUE THREAD

**Issue by wottop** [mattbertolini/liquibase-slf4j#15]
We are using liquibase-slf4j 4.1.0 and have been using slf4j 1.7.36.

When we up it to slf4j 2.0.0 we get 

java.lang.ClassCastException: class org.slf4j.helpers.NOPLoggerFactory cannot be cast to class ch.qos.logback.classic.LoggerContext (org.slf4j.helpers.NOPLoggerFactory and ch.qos.logback.classic.LoggerContext are in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @e077866)

**Comment by mattbertolini** [comment]
Hi @wottop. Thanks for the report. Could I get a little more information from you? Here's some questions I have:

1. It looks like you're using Apache Tomcat. What version of Tomcat are you using? Are you using it as an embedded web server or are you deploying a WAR file to a standalone server?
2. What version of Liquibase are you using?
3. Looks like you're trying to use Logback as your logging implementation for Slf4j. Is that correct?
4. What version of the JDK are you running with?
5. Any additional frameworks involved here (e.g. Spring Boot, Dropwizard, etc) that I should be aware of?

Most of the time problems like these are more related to SLF4J than to this library specifically. This library just calls the public API of SLF4J so if there's a classpath issue it's beyond my control. I am a bit curious about the module loader message in the stacktrace. That leads me to believe that the JPMS might be in effect and I'd like to narrow that down. I'd like to try and recreate the issue. Do you have a minimal app to recreate? If not, give me as much detail about it so I can create one. Thanks!

**Comment by wottop** [comment]
1. Tomcat version 9.0.30. Deploying a WAR
2. LIquibase version 4.12
3. As far as I can tell
4. 11
5. Not sure if RestEasy falls into this category.
I don't have a minimal app, but the repo is here:
https://github.com/candlepin/candlepin

Thanks for the help

**Comment by mattbertolini** [comment]
What version of Logback are you using? Slf4j 2.x is a breaking change and not compatible with Logback 1.2.x. Version 1.3.x is required when using Slf4j 2.x

**Comment by wottop** [comment]
We are using ch.qos.logback:logback-classic:1.2.11
I'll up that to 1.3 and see how it goes.

**Comment by wottop** [comment]
That appears to clear up our issues. Thanks for the help.

**Comment by mattbertolini** [comment]
Great! Happy to help!
