### ISSUE TITLE
Cannot find default log service

### ISSUE THREAD

**Issue by ItsRainingHP** [mattbertolini/liquibase-slf4j#19]
No matter what I do I get `Cannot find default log service error` trying to use liquibase. Every forum I read says to use this library but even included I still get `Cannot find default log service error`. Any assistance would be appreciated.

I verified both your class files are present in my Jar along with slf4j-simple. What am I missing? Using liquibase 4.29.1

**Comment by mattbertolini** [comment]
How are you running Liquibase? CLI? Maven? Servlet? Spring? WAR? If it's CLI, I don't think its supported as Liquibase locks down the logging to make sure it goes to stdout.

**Comment by ItsRainingHP** [comment]
Here is my implementation code for liquibase:

```
    private void updateSchema() {
        try {
            Class.forName(this.databaseConfigurationSection.getDriver());
            try (Connection connection = DriverManager.getConnection(
                    this.databaseConfigurationSection.getConnectionURL(),
                    this.databaseConfigurationSection.getUsername(),
                    this.databaseConfigurationSection.getPassword())) {
                Database database = liquibase.database.DatabaseFactory.getInstance().findCorrectDatabaseImplementation(new JdbcConnection(connection));
                Liquibase liquibase = new Liquibase(RDS.getInstance().getDataFolder() + "/bin/schemas/changelog.xml", new ClassLoaderResourceAccessor(), database);
                liquibase.update(new Contexts(), new LabelExpression());
            } catch (SQLException | LiquibaseException e) {
                LoggerAPI.sendLoggerSevereColorized(RDS.getInstance(), "Failed to update schema: " + e);
            }
        } catch (ClassNotFoundException ex) {
            LoggerAPI.sendLoggerSevereColorized(RDS.getInstance(), "Failed to update schema: " + ex);
        }
    }

**Comment by mattbertolini** [comment]
A reproducer project would be best to track down your problem. If you have that it would be greatly appreciated. In lieu of that, could you provide me your classpath output, JDK version, OS version, build tool (e.g. maven, gradle, ant), output artifact (e.g. jar/war/ear). 

The error comes from Liquibase [here](https://github.com/liquibase/liquibase/blob/93e5e6e2c8c8578efe13c62015d8da2f744a303f/liquibase-standard/src/main/java/liquibase/Scope.java#L107). This strike me as a classpath issue where something is missing that is required for liquibase to run.

**Comment by ItsRainingHP** [comment]
It would take quite a bit of refactoring to make a test example. My project is private but if you are willing, I can temporarily invite you to take a look.

**Comment by mattbertolini** [comment]
Let's try and avoid that for now. I've created an example project that verifies the functionality in a minimal implementation. Check it out and see if anything jumps out to you.

[liquibase-embedded-test.zip](https://github.com/user-attachments/files/16571391/liquibase-embedded-test.zip)

**Comment by ItsRainingHP** [comment]
Could the issue be that I load liquibase externally? I do not shade it in and load the jar externally at runtime.

**Comment by mattbertolini** [comment]
File size limit? Intriguing. Not sure I've ever encountered a platform that limits that. Is this an Android app? 😬 

It very much could yes. All of the jars involved in liquibase (liquibase, liquibase-slf4j, logging impl jar, jdbc driver, etc) all need to be loaded using the same Classloader or a Classloader needs to know where to find all of them if they are loaded differently. Your ClassLoaderResourceAccessor will need to be passed a Classloader if the thread context classloader is not adequate to do the job. That or you need to use a different ResourceAccessor that isn't dependent on classloaders. Not knowing the specifics of what you mean by loading it externally, I would have to say it's a definitely possibility.

**Comment by ItsRainingHP** [comment]
Proper context thread was the answer. Thank you!
```
        ClassLoader previousContextClassLoader = Thread.currentThread().getContextClassLoader();
        try {
            Thread.currentThread().setContextClassLoader(RCore.getInstance().getLibraryLoader().getURLClassLoaderAccess().getClassLoader());
            Class.forName(this.databaseConfigurationSection.getDriver());
            try (Connection connection = DriverManager.getConnection(
                    this.databaseConfigurationSection.getConnectionURL(),
                    this.databaseConfigurationSection.getUsername(),
                    this.databaseConfigurationSection.getPassword())) {
                Database database = liquibase.database.DatabaseFactory.getInstance().findCorrectDatabaseImplementation(new JdbcConnection(connection));
                Liquibase liquibase = new Liquibase("/bin/schemas/changelog.xml", new DirectoryResourceAccessor(RDS.getInstance().getDataFolder()), database);
                liquibase.update(new Contexts(), new LabelExpression());
            } catch (SQLException | LiquibaseException e) {
                LoggerAPI.sendLoggerSevereColorized(RDS.getInstance(), "Failed to update schema: " + e);
            }
        } catch (Exception ex) {
            LoggerAPI.sendLoggerSevereColorized(RDS.getInstance(), "Failed liquibase scope: " + ex);
        } finally {
            Thread.currentThread().setContextClassLoader(previousContextClassLoader);
        }

**Comment by mattbertolini** [comment]
Happy to help! 😄

**Comment by ItsRainingHP** [comment]
After further testing, proper context for the class loader did fix the startup errors noted above. However, it still does not use this libraries logging.

I tried locally adding the files in (editing them to use the proper logger for my environment), and loading the class files in the same context as the liquibase initialization code above but no luck. I am trying to override liquibase logger so it does not use System.out or System.err.

```
[18:25:52 WARN]: Nag author(s): '[ItsRainingHP]' of 'JAR' about their usage of System.out/err.print. Please use your plugin's logger instead.

**Comment by mattbertolini** [comment]
If the plugin isn't loading it's because Liquibase can't find it. That means it's either still a classpath/classloader issue or a service loader issue. Are you using a shaded or fat jar? If so, you need to make sure the ServiceLoader manifest files are merged together and present. Liquibase uses the ServiceLoader to find all of its components, including its own. So so if two manifest files have the same name, the shaded jar will only select one unless the files are merged together. Most shade plugins have a mechanism to do this for you but if you're doing it manually, you need to make sure they are merged together.

[Liquibase's LogService ServiceLoader manifest](https://github.com/liquibase/liquibase/blob/master/liquibase-standard/src/main/resources/META-INF/services/liquibase.logging.LogService)
[Plugin LogService ServiceLoader manifest](https://github.com/mattbertolini/liquibase-slf4j/blob/main/src/main/resources/META-INF/services/liquibase.logging.LogService)

**Comment by ItsRainingHP** [comment]
Liquibase is loaded at runtime using an external jar. It is not shaded or fat jar as you say. If I shade liquibase in, it becomes far too large. Jar must stay under 4 mb, I know its annoying and everyone agrees but nothing we can do about it. 

I am not sure how to change or override manifest's for a library loaded at runtime.

**Comment by mattbertolini** [comment]
I'm not really sure what else to say. I have very little information to go on to help you diagnose this issue. Your implementation is very much non-standard and I've confirmed the library is functioning as intended.  Without a reproducer I'm not sure there's anything else I can do.

**Comment by ItsRainingHP** [comment]
I understand. Thanks for the help! I will post the resolution if I find one!

**Comment by ItsRainingHP** [comment]
I managed to get it to use your class files by editing the appropriate manifest file and injecting your class files into the jar before loading the jar during runtime. The liquibase logs are successfully printing to the appropriate logger.

The final issue is the logs still print to the System.out logger (which results in duplicate entries and the warning I am using the wrong logger). I am not sure how to avoid that issue yet, but anyone reading this knows the direction to take.
