### ISSUE TITLE
Bug: Log level `OFF` (JUL) is mapped to `ERROR` (SLF4J)

### ISSUE THREAD

**Issue by joschi** [mattbertolini/liquibase-slf4j#22]
`Slf4jLogger#log(Level, String, Throwable)` doesn't handle [`Level.OFF`](https://docs.oracle.com/javase/8/docs/api/java/util/logging/Level.html#OFF) from `java.util.logging` and logs the respective messages on `ERROR` level instead.

https://github.com/mattbertolini/liquibase-slf4j/blob/v5.1.0/src/main/java/com/mattbertolini/liquibase/logging/slf4j/Slf4jLogger.java#L79-L92

**Comment by mattbertolini** [comment]
Hi @joschi. I think this was reported last week in #20 and that reporter confirmed it was fixed with PR #21. I released version 5.1.0 with this change. Is there another failure case I am unaware of that is still triggering?

**Comment by joschi** [comment]
You're right. I stumbled over it in context of https://github.com/dropwizard/dropwizard/pull/9604 but that was still with liquibase-slf4j 5.0.0.

The linked PR which ended up in v5.1.0 should fix this. 😄
