### ISSUE TITLE
Liquibase 3.4.0 - Always print info log message

### ISSUE THREAD

**Issue by regis-leray** [mattbertolini/liquibase-slf4j#4]
I added the dependency ```liquibase-slf4j``` latest , but it doesnt seem to pick the logger ```Slf4jLogger ``` during the startup on unit integration test, and always use the DefaultLogger.

Im using logback + slf4j. 

i cannot control the level of the log from the logback configuration file (logback-test.xml), always print the INFO from liquibase

```
<logger name="liquibase" level="WARN" />
````

[INFO] +- org.springframework.data:spring-data-commons:jar:1.9.1.RELEASE:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.8:compile
[INFO] |  \- org.slf4j:jcl-over-slf4j:jar:1.7.8:runtime

[INFO] +- org.liquibase:liquibase-core:jar:3.4.0:test
[INFO] +- ch.qos.logback:logback-classic:jar:1.1.2:test
[INFO] |  \- com.mattbertolini:liquibase-slf4j:jar:1.2.1:test
[INFO] |  \- ch.qos.logback:logback-core:jar:1.1.2:test

How liquibase know to use ```Slf4jLogger``` and not ```DefaultLogger```

**Comment by mattbertolini** [comment]
It's a bug in Liquibase 3.4.0, not the logger. Version 3.3.5 does not seem to have this issue so I recommend downgrading until Liquibase fixes it.

**Comment by mattbertolini** [comment]
Dug into Liquibase code. I think I found where they caused the regression. I filed a bug upstream for the issue. Follow here: https://liquibase.jira.com/browse/CORE-2443

**Comment by regis-leray** [comment]
@mattbertolini thanks i really appreciate.

**Comment by mattbertolini** [comment]
I submitted a [pull request](https://github.com/liquibase/liquibase/pull/462) to Liquibase for a fix to their `LogFactory`. I have done all I can to move this forward. It is now in the hands of the Liquibase devs to fix it and release a new version. I would say start to comment their to get the issue more visibility.

**Comment by regis-leray** [comment]
@mattbertolini really appreciate. i will ping them.
thanks

**Comment by mattbertolini** [comment]
Liquibase 3.4.1 has now been released with the fixes. I have added a note to the README file about the issues in version 3.4.0 so other users will not run into the same problems. With these actions I consider this issue resolved. Closing this ticket.

**Comment by regis-leray** [comment]
Thank you so much
